# Generated by Django 5.0.3 on 2024-03-09 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0002_pokemon_delete_superheromodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='PokemonModel',
        ),
    ]
