# Generated by Django 5.0.3 on 2024-03-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0003_rename_pokemon_pokemonmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmodel',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonmodel',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
