# Generated by Django 5.0.3 on 2024-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0004_alter_pokemonmodel_height_alter_pokemonmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmodel',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
