# Generated by Django 5.0.3 on 2024-03-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_api', '0005_alter_pokemonmodel_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmodel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pokemonmodel',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
